on:
  push:         {"branches": ["master"]}
  pull_request: {"branches": ["master"]}

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - run: 'sudo apt-get install -y zsh'
    - run: 'make'
    - run: 'make check'
